apiVersion: v1
kind: Pod
metadata:
  name: tf-pod
spec:
  containers:
    - name: tf-container
      image: tensorflow/tensorflow:latest-gpu
      resources:
        limits:
          tencent.com/vcuda-core: 100
          tencent.com/vcuda-memory: 31
          #nvidia.com/gpu: 1 # requesting 1 GPUs